language: node_js
node_js:
  - 8.9.4

branches:
  only:
    - master
    - /v\d+\.\d+\.d+$/
    - feature/two-page-image-modal

cache:
  directories:
    - "node_modules"

stages:
  - PR checks ✅
  - name: Ship It 🚢
    if: branch=master AND type=push
jobs:
  include:
    - stage: PR checks ✅
      env:
        - NAME=Unit Tests
      script: npm run test
      after_script:
        - codecov
    - stage: PR checks ✅
      env:
        - NAME=Validation Checks
      script:
        - ./.travis/validate_changes_for_merge.sh
        - git grep "feature/two-page-image-modal" -- .travis.yml && echo "please revert this commit before merging to master"
    - stage: Ship It 🚢
      env:
        - NAME=Publish
      script: semantic-release

notifications:
  webhooks: https://www.travisbuddy.com/
