version: "2.1"
services:
    studio-frontend:
        extends:
            file: docker-compose.yml
            service: studio-frontend
        environment:
            - RUNNING_ON_LINUX=1
        # This works because docker-compose will merge the files together.
        # Mac host machines cannot publish ports in network_mode='host'.
        # Linux users require network_mode='host' because there's no equivalent to docker.for.mac.localhost
        network_mode: host
